kind: Secret
ansible_user: ENC[AES256_GCM,data:KdouUftJ0Q==,iv:QEV2oqrXR1uKj8PW20IYTuozKgdp80/2+yg5UtMgl2U=,tag:CrYj3diPjESsL5ItIKYKow==,type:str]
ansible_become_pass: null
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-26T23:01:19Z"
    mac: ENC[AES256_GCM,data:DFWn8j5zTHLixuHnnX6jM50ilEA2ZXEuvfNGyIIBpLDsQ6M6S4UrG8KMWhtqFuHFbMe++rxfyr7mN/xsJq3Yvb0rJPZo1lbq0PmBjiTlxjBjLvwzg4kBN8VRa4Pg9/ZnRodYw+1vq82O+gjEbgQ6q9ezWJfcxfv2wlvy2Um7M2I=,iv:uoMGtngoYuGD5Hxh55P2yLXYd/aqUbJm6Vmr263qVUE=,tag:LwtKpsU4uOcrMGng34t4TA==,type:str]
    pgp:
        - created_at: "2021-10-26T23:01:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4usUSIbBXpjAQ/+NVCXigLE0MWSE6Z5Qu7jqn4r2tIWgCpi+DVJbCKtMSW7
            m5UkbgRHVMO/DDD6BozRDkyCMj81mDhoWK6BBytglV5hJgt+nNo+g0wqWm53Sw0N
            uyOSCQsi93/Dj1bTWsoXSSqQdjA8Mi9qh+xMnPmC34vzfGQ+0OVDCPYx507KY5LP
            pB0Gy6q9pNJEMwyLxcxT70+6UbYYyThebKY1ch5n4V4V4YcOZoWaPi5aMxIHE8Mb
            fMnUzTY7/lMZNBxceIuoIayd9X6ZCBHOrfEV0DicI4fDB9Fz97rZSlzW3/W2R3M9
            wzxGBgfdiLik4dD89QLMWaCGNrMT5+ZDAFqMXEBasAcByAL/RV9bY42h94ci86/s
            R/tlB/0nJvVzJzg14cQTAvYTBJKBbsjAt4qyQizrSOp6sm87iviU4nU5zrVYRtDU
            adt07xzhZG3bqpbf8NpP3aUzHKMoAzqGN4VhV3ehPCBcDi97AIc88ppE1j+VhYIG
            9VyR/NftYlsRsj6r2fcrk+pqL9Fyk8zTaBYSCs4QR94ZVRqg/DWGp6jQbT637Npc
            dmi/AmeSJqu0xZOjSnWwdMJwva2X+RMRcaYMhD1EPiVfsfbFpuPNutGlgjEEsPl0
            kgNWLZQm0L7De8Xgl4SJZqn5PSDGguDFB6/u9L5W3cbVIJdzbqINRKCr515gpT7S
            XgH3mo1B9IZdmXoku1Oxn8FKM45cCM2QCVjLI6ShxOLU3yhuXpT3QdBEdS7jnX8p
            jst3/c5221i/bKyxpkjoE2VX2pwB6obydK0d8tc10NN2nPD7/r6YJsY8KFi01bo=
            =N1SV
            -----END PGP MESSAGE-----
          fp: 942B2F0CAB0D5D9862F3853F364E795D254254FA
    unencrypted_regex: ^(kind)$
    version: 3.7.1
