# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:qRqcC3lW5/ROCQ==,iv:eNmGcmbfY1Qnopt5yU4aq37KfIrjt/Qhh5BJ3GifM7k=,tag:RY0jzKqZw65VfOloiq2zXA==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:NA0TD2wIWGZ17FrKbncWgv5W9s0=,iv:zdsBBaRwnEbcmW64XsRppVyrKyZ5W0dW3FpRc0pCvVI=,tag:cXATOsaQrbmp/Qe7GBUu3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-10-26T23:01:17Z"
    mac: ENC[AES256_GCM,data:+tr5kERwRK+odVkIvxe2GqiDQEVUlmafglcpUpqHHXaaQIa4SG6yprVTHVjkdIHMSoTrE25sQ9EJ/WQTvTvDPPa8/HOema2sLOdn2em0kuVVxlqFI7XzEpnypM7RCOwdWXObVHBnFFuXTEzwJDx7OQ6BHvHH4qm/ryClElEnGus=,iv:NViWYUSf4ewfrzK2Sg5wkO/KC3B0+b48ddD47d6ej0k=,tag:BpaMLXRZDVxk1Nn/BjqGsQ==,type:str]
    pgp:
        - created_at: "2021-10-26T23:01:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4L8jeOiYgUVARAAtzqr0mCNj56vObX3EYtmwua87NBws88at2s/4XcaKEPB
            G+qrJZOi/sBBZO8ibMCMcDcl7GDLrNCcomAxn95OyayWu5KpbnHp1ezl7Wav8SQz
            BZ6Mk61OosytKoOGx1JxTqJY4CDCRGn0iQT3FbNQNfm2b6TuuuYYgeIDCzVyRtzs
            KFsCNujpo8Sb7M+RZWBTwhEF7BaLniKDQywXbVy2AjNUFeyYr9fyqYw+nJwA16l+
            TifSK0+wwfaMAJEld7ogt5XK9ssIyPLAzjRH3GY+aoMCE3BFWakmGCVnfigi6lrB
            UqkAKBRaZDMifSkDCjmsa1aHv5Vnp9xrfn/LB5CTf51U7sxe73r2zMoHjfRlwfIY
            7akODU6obvhA239VpqPIDO0Y42Itasd6dsqc02/se22DcwBVWooeTwWCObKtbTVr
            4RCfBdnaZcaFYiHw9tc+q/jJrcv3JPioAEIpJUIKrZIc5fobLQAyKX2llNPGHT05
            AG3ilTlIveIHc2oam1v687vEVgbAF2ST/gZGHn0cZ0trqQaTgEwbdRpOm/EzM21U
            u9UGO+Bqurao+9YvsygY4sfH1WfVuRpm/L5wyfBMNGPSrLAHmmHakY6C35lyBD1n
            HMNQj+7yWuPtNRwCjCOfFg43aYURUT/goE27b1sw5tWoMydq0O7bjDaXxtkwyQLS
            XAGUtluRcoR2f1o7aeQxNqCFndK3fK3oG41Njs/I/shwkaennpm3DWo7zaATnUNf
            8BUw3+1Tr9iGRfaLwTtx4K8v3qvKG4hw6seJe0GOQscT2/1FvllVPOqhv+0Q
            =589D
            -----END PGP MESSAGE-----
          fp: C38012C65A8169390084BDAAE0F851CDE00A1F63
        - created_at: "2021-10-26T23:01:16Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4usUSIbBXpjAQ//fe06mi/5fwZ6wE5lLn0Pi87PZ/G7m1gPmRYCQRopRK4/
            HLrHuQoUR0O+HmCX0cryOAEH4EiBH/4WeMV4XzCFqLgYIA9w/xxbsPLS8iEaGhA5
            h/0eGUqDG+5XuBe7mBZqWN6VmVQxgHQe4gw3H516YbiCkqwhszuAknCcQgmnCb9+
            tyOG4H8W5rXXaNwg3fdMWDn/Gtu5tIlVFs9BYFOH/um0+ITKs9ZAZK8984wItdjb
            FlKDU1CNM6LZJR6uGgEWm8FEKb4RmXrrxCZminirriv9HYxLwqvFLu2+M0+oU+h4
            0DRE0+GFXecABFYtg26wIJ5of6qN926YErU5mniLIfmYU83a0VG/DX/jsCetf5eH
            P2suX23A5IlvViqMXsMGwTTjZO51pLNgTcBXLZ5YmZWVo+IieGl0AkVM95oB2tbi
            ILTeDcABnB+Tzbhonp0pQSzDEK+vS1mjgJjtZGW8fxt6Ng1LUz057haduSlXEzX2
            Jayy4W/NuszmyO9g1ZUX1k5NXdNgZ4k98Bjk+QI4B+84vxmHLFmRwaUBZbs6g5pe
            mIjnREGnd/F1QO6k8+T+kS0LIYxDgWQVHeeUyU9UpCB0nPD7jUdolaxHHL6sy5uL
            9sn80/phFV2idsl60blp+BaDlrcve6WCOcj8lrxJsFVz0we+78Jcv0sqaPigg9bS
            XAHfBcrtzicl2RIMzVt+hBIQYYsEFqLNBJrXB7CpV42RXsRiP1sHWtsw98Kr6KwC
            D0HimDjoL3tYDnM5MHxdr5ESCD+7V88vsbaHazfCHxrCjuCHZkXQBthuanGp
            =6fQu
            -----END PGP MESSAGE-----
          fp: 942B2F0CAB0D5D9862F3853F364E795D254254FA
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
